### ISSUE TITLE
No complete output

### ISSUE THREAD

**Issue by SamarthMR** [serhattsnmz/turtle#2]
Output is incomplete...username is not taking and further it's not running
![15656268691926093870525699795610](https://user-images.githubusercontent.com/54024433/62880579-5bb07a80-bd4b-11e9-96f5-dba735c21a34.jpg)

**Comment by SamarthMR** [comment]
Username is not getting accepted
Password is not shown
Further code is not running

**Comment by serhattsnmz** [comment]
Hi @SamarthMR ,

I've checked them all, but I didn't see any issue about that. Can you tell me more about your problem, please? 

Beside, I recommended to install suitable version of CromeDriver for your computer, based on you Chrome web browser. 

Thanks.
