### ISSUE TITLE
Is it possible to download posts in separate folder!!

### ISSUE THREAD

**Issue by hustlerwolf** [serhattsnmz/turtle#5]
Hey @serhattsnmz 

First of all thanks for this python scripts for downloading images from Instagram, it helps a lot. Due to the recent increase usage of album type posts, I was wondering if we can download all posts to separate folder so if any post will have more than one image that all will go to the same folder, so we can easily keep track of all posts separately.

Thanks in advance

**Comment by serhattsnmz** [comment]
Hi @hustlerwolf ,

Thanks for request. 

In my opinion, there would be a lot of unnecessary folders when we do it your way. Besides, how would you name the folders? 

Although I don't like it, I'd add that in the future as optional. 

Thanks.
